example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_items

app_name = 'katalog'

urlpatterns = [
    path('', show_items, name='show_items'),
]

mywatchlist/urls.py
# TODO: Implement Routings Here
from django.urls import path
from mywatchlist.views import show_watchlist
from mywatchlist.views import show_watchlist_html
from mywatchlist.views import show_watchlist_xml
from mywatchlist.views import show_watchlist_json

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_watchlist, name='show_watchlist'),
    path('html/', show_watchlist_html, name='show_watchlist_html'),
    path('xml/', show_watchlist_xml, name='show_watchlist_xml'),
    path('json/', show_watchlist_json, name='show_watchlist_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import delete_task, register_account, user_login, user_logout, show_todolist, create_task, change_status, delete_task, show_json, add_task_ajax, delete_task_ajax

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register_account, name='register_account'),
    path('login/', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout'),
    path('create-task/', create_task, name='create_task'),
    path('change-status/', change_status, name='change_status'),
    path('delete-task/', delete_task, name='delete_task'),
    path('json/', show_json, name='show_json'),
    path('add/', add_task_ajax, name='add_task_ajax'),
    path('delete/<int:id>', delete_task_ajax, name='delete_task_ajax'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class MyWatchlistItem(models.Model):
    watched = models.BooleanField()
    title = models.CharField(max_length=255)
    rating = models.FloatField()
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User, models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.

def show_items(request):
    response = {
        'list_item': CatalogItem.objects.all(),
        'name': "Fabian Akmal Arkandion",
        'npm': "2106750660"
    }
    return render(request, 'katalog.html', response)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchlistItem
from django.http import HttpResponse
from django.core import serializers

# TODO: Create your views here.

def show_watchlist(request):
    return render(request, 'mywatchlist_home.html')

def show_watchlist_html(request):
    data = MyWatchlistItem.objects.all()
    watched = 0
    not_watched = 0
    text_response = ""

    # Bonus
    for item in data.values():
        if (item.get("watched") == True):
            watched += 1
        else:
            not_watched += 1
    
    if watched >= not_watched:
        text_response = "Selamat, kamu sudah banyak menonton!"
    else:
        text_response = "Wah, kamu masih sedikit menonton!"

    context = {
        'watchlist': data,
        'text_response': text_response
    }
    return render(request, 'mywatchlist.html', context)

def show_watchlist_xml(request):
    data = MyWatchlistItem.objects.all()

    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_watchlist_json(request):
    data = MyWatchlistItem.objects.all()

    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from datetime import date
from random import randint
from telnetlib import STATUS
from urllib import response
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from todolist.models import Task
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from django.contrib.auth.models import AnonymousUser

# Create your views here.

def register_account(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been created!')
            return redirect('todolist:user_login')
    
    context = {'form':form}
    return render(request, 'register_account.html', context)

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse('todolist:show_todolist'))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Wrong username or password!')

    context = {}
    return render(request, 'user_login.html', context)

def user_logout(request):
    logout(request)
    return redirect('todolist:user_login')

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    username = request.user.username

    context = {
        'todolist': Task.objects.filter(user=request.user),
        'username': username,
    }
    return render(request, 'todolist.html', context)

@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == "POST":
        user = request.user
        title = request.POST.get('title')
        description = request.POST.get('description')
        task = Task(user=user, date=date.today(), title=title, description=description)
        task.save()

        messages.success(request, 'A task has been added!')
        return redirect('todolist:show_todolist')
    
    context = {}
    return render(request, 'create_task.html', context)

@login_required(login_url='/todolist/login/')
def change_status(request):
    task = Task.objects.get(pk=request.POST['pk'])
    task.is_finished = not task.is_finished
    task.save()

    messages.success(request, 'A task status has been changed!')
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def delete_task(request):
    task = Task.objects.get(pk=request.POST['pk'])
    task.delete()

    messages.success(request, 'A task has been deleted!')
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def show_json(request):
    data = Task.objects.filter(user=request.user.id)

    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/todolist/login/')
def add_task_ajax(request):
    if request.method == "POST":
        user = request.user
        title = request.POST.get('title')
        description = request.POST.get('description')
        task = Task(user=user, date=date.today(), title=title, description=description)
        task.save()

        return HttpResponse("Task: " + title + " have been added")

    return HttpResponse(status=400)

@login_required(login_url='/todolist/login/')
def delete_task_ajax(request, id):
    task = Task.objects.get(pk=id)
    title = task.title
    task.delete()

    return HttpResponse("Task: " + title + " have been deleted")

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 2 Assignment PBP/PBD</h1>

  <h3>Name: </h3>
  <b>{{ name }}</b>

  <h3>Student ID: </h3>
  <b>{{ npm }}</b>

  <h3 style="text-align:center">TABLE</h3>
  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in list_item %}
        <tr>
            <th>{{ item.item_name }}</th>
            <th>{{ item.item_price }}</th>
            <th>{{ item.item_stock }}</th>
            <th>{{ item.rating }}</th>
            <th>{{ item.description }}</th>
            <th>{{ item.item_url }}</th>
        </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1 style="text-align: center; color: blue">MOVIE WATCHLIST</h1>
  <table>
    <tr>
      <th>Watched</th>
      <th style="width: 150px">Title</th>
      <th>Rating</th>
      <th style="width: 150px">Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in watchlist %}
        <tr>
            <th>{{ item.watched }}</th>
            <th>{{ item.title }}</th>
            <th>{{ item.rating }}</th>
            <th>{{ item.release_date|date:"j F Y" }}</th>
            <th>{{ item.review }}</th>
        </tr>
        <tr>
        </tr>
    {% endfor %}
  </table>
  <br>
  <h3>Feedback:</h3>
  <b>{{ text_response }}</b>

 {% endblock content %}

mywatchlist/templates/mywatchlist_home.html
{% extends 'base.html' %}

 {% block content %}

  <h1 style="text-align: center; color: blue">MOVIE WATCHLIST</h1>
  <a href="https://ark-tugas2pbp.herokuapp.com/mywatchlist/html">Click this link to show watchlist in HTML</a>
  <br>
  <br>
  <a href="https://ark-tugas2pbp.herokuapp.com/mywatchlist/xml">Click this link to show watchlist in XML</a>
  <br>
  <br>
  <a href="https://ark-tugas2pbp.herokuapp.com/mywatchlist/json">Click this link to show watchlist in JSON</a>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>

	<nav class="navbar navbar-expand-lg bg-light">
		<div class="container-fluid">
			<a class="navbar-brand">ARK™</a>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<a class="nav-link active" aria-current="page">User: {{ username }}</a>
				</li>
				<form class="d-flex">
					<a class="btn btn-danger" href="{% url 'todolist:user_logout' %} " role="button">Logout</a>
				</form>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
					Menu
					</a>
					<ul class="dropdown-menu">
					<li><a class="dropdown-item" href="{% url 'todolist:user_login' %}">Login</a></li>
					<li><a class="dropdown-item" href="{% url 'todolist:register_account' %}">Register</a></li>
					<li><hr class="dropdown-divider"></li>
					<li><a class="dropdown-item" href="{% url 'todolist:show_todolist' %}">To-Do List</a></li>
					<li><a class="dropdown-item" href="{% url 'todolist:create_task' %}">Create Task</a></li>
					</ul>
				</li>
				</ul>
			</div>
		</div>
	</nav>
</head>

<body>
  {% block content %}
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
	<script>
		$(document).ready(function(){
			$('[data-toggle="popover"]').popover();
		});
	</script>
  {% endblock content %}
</body>

</html>

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create Task</title>
{% endblock meta %}

{% block content %}
<br>
<h1 style="color: #0d6efd; text-align: center; font-weight: bold; font-family: Tahoma">Create Task</h1>
<br>

<div class="create-task" style="text-align:center">

    <form method="POST">
        {% csrf_token %}
        <div class="card border-dark" style="margin:auto; width:50%; padding:10px">
            <h1>Add your tasks here:</h1><br>
            <table>
                <tr>
                    <td>Task title: </td>
                    <td><input type="text" name="title" placeholder="Title" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Description: </td>
                    <td>
                        <textarea name="description" placeholder="Task description" class="form-control"></textarea>
                    </td>
                </tr>
    
                <tr>
                </tr>
            </table>
            <br>
            <button type="submit" class="btn btn-primary mx-auto" style="width:15%;">Add task</button>
        </div>
    </form>
    
    {% if messages %}
        <br>
        <ul style="margin:auto; width:30%">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <br>
    <div class="card text-center mx-auto" style="width:30%;">
        <div class="card-body">
            <h5 class="card-title">View your to-do list here:<br>
                <div class="card-text">
                    <a href="{% url 'todolist:show_todolist' %}">To-Do List</a>
                </div>
            </h5>
        </div>
    </div>
    <br>

</div>

{% endblock content %}

todolist/templates/register_account.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block content %}  
<br>
<h1 style="color: #0d6efd; text-align: center; font-weight: bold; font-family: Tahoma">Account Registration</h1>
<br>

<div class="registration" style="text-align:center">

    <div class="card border-dark" style="margin:auto; width:50%; padding:10px">
        <form method="POST">  
            {% csrf_token %}
            <h1 style="text-align:center">Registration Form</h1><br> 
            <table>  
                {{ form.as_table }}
            </table>
            <br>
            <button type="submit" class="btn btn-primary mx-auto" style="width:15%;">Submit</button>
        </form>
    </div>

    {% if messages %}
        <br>
        <ul style="margin:auto; width:30%">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}  

    <br>
    <div class="card text-center mx-auto" style="width:30%;">
        <div class="card-body">
            <h5 class="card-title">Already have an account?<br>
                <div class="card-text">
                    <a href="{% url 'todolist:user_login' %}">Login to your account</a>
                </div>
            </h5>
        </div>
    </div>
    <br>

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<title>To-Do List</title>
{% endblock meta %}

{% block content %}
<br>
<h1 style="color: #0d6efd; text-align: center; font-weight: bold; font-family: Tahoma">To-Do List</h1>

<div class = "todolist">

    <h1 style="text-align: center">Hi, {{ username }}! Here's your to-do list:</h1><br>

    <div id="ajax-todolist"></div>

    <div class="card text-center mx-auto" style="width: 30%;">
        <div class="card-body">
            <h5 class="card-title">Don't have an account yet?<br>
                <a href="{% url 'todolist:register_account' %}">Create Account</a>
            </h5>
            <br>
            {% if messages %}
                <div class="card-text">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </div>
                <br>
            {% endif %}
            <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addTaskModal">Add task</button>
            <a href="{% url 'todolist:user_logout' %}" class="btn btn-danger">Logout</a>
        </div>
    </div>
    <br>
</div>

<div class="modal fade" id="addTaskModal" tabindex="-1" aria-labelledby="addTaskModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="addTaskModalLabel">Add Task</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="POST" id="add-task">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="card border-dark" style="margin:auto; width:100%; padding:10px">
                        <h5>Add your task here:</h5>
                        <table>
                            <tr>
                                <td>Task title: </td>
                                <td><input type="text" name="title" placeholder="Title" class="form-control"></td>
                            </tr>
                                    
                            <tr>
                                <td>Description: </td>
                                <td>
                                    <textarea name="description" placeholder="Task description" class="form-control"></textarea>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary" id="btn-add">Add</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    function renderTodolist() {
        $.get("/todolist/json", function(data) {
            console.log(data);
            var todolist = ""
            for (i = 0; i < data.length; i++) {
                todolist += `
                <div class="card border-dark" style="margin:auto; width:90%" data-toggle="popover" title="${data[i].fields.title}" data-content="Created at ${data[i].fields.date}">
                    <h4 class="card-header">${data[i].fields.title}</h4>
                    <div class="card-body bg-light" id="ajax-todolist">
                        <h5 class="card-title">${data[i].fields.description}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Created at ${data[i].fields.date}</h6>
                        <p class="card-text">${data[i].fields.is_finished ? "Status: Finished":"Status: Not Finished"}</p>
                        <table>
                            <td>
                                <form method="POST" action="{% url 'todolist:change_status' %}" style="margin: 0; padding: 0">
                                    {% csrf_token %}
                                    <input type="number" name="pk" value="${data[i].pk}" hidden>
                                    <button type="submit" class="btn btn-primary">Change status</button>
                                </form>
                            </td>
                            <td style="padding-left:10px">
                                <form method="POST" id="delete-task" action="{% url 'todolist:delete_task' %}" style="margin: 0; padding: 0">
                                    {% csrf_token %}
                                    <input type="number" name="pk" value="${data[i].pk}" hidden>
                                    <button type="submit" class="btn btn-danger">Delete task</button>
                                </form>
                            </td>
                        </table>
                    </div>
                </div>
                <br>
                `
            }
            document.getElementById("ajax-todolist").innerHTML = todolist
        });
    }
    function closeModal() {
        $('#addTaskModal').modal('hide');
    }
    $(document).ready(function(){
        renderTodolist();
        $('#add-task').submit(function() {
            // create an AJAX call
            $.ajax({
                data: $(this).serialize(), // get the form data
                method: 'POST', // GET or POST
                url: "{% url 'todolist:add_task_ajax' %}",
                // on success
                success: function(response) {
                    alert(response);
                    closeModal();
                    renderTodolist();
                }
            });
            return false;
        });
        $('#delete-task').submit(function() {
            // create an AJAX call
            var id = $(this).find('input[name="pk"]').val()
            $.ajax({
                data: $(this).serialize(), // get the form data
                method: 'POST', // GET or POST
                url: `/todolist/delete/${id}`,
                // on success
                success: function(response) {
                    alert(response);
                    renderTodolist();
                }
            });
            return false;
        });
    });
</script>
{% endblock content %}

todolist/templates/user_login.html
{% extends 'base.html' %}

{% block meta %}
<title>User Login</title>
{% endblock meta %}

{% block content %}
<br>
<h1 style="color: #0d6efd; text-align: center; font-weight: bold; font-family: Tahoma">User Login</h1>
<br>

<div class = "login" style="text-align:center">

    <form method="POST">
        {% csrf_token %}
        <div class="card border-dark" style="margin:auto; width:50%; padding:10px">
            <h1>Login</h1><br>
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>
    
                <tr>
                </tr>
            </table>
            <br>
            <button type="submit" class="btn btn-primary mx-auto" style="width:15%;">Login</button>
        </div>
    </form>

    {% if messages %}
        <br>
        <ul style="margin:auto; width:30%">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
    
    <br>
    <div class="card text-center mx-auto" style="width:30%;">
        <div class="card-body">
            <h5 class="card-title">Don't have an account yet?<br>
                <div class="card-text">
                    <a href="{% url 'todolist:register_account' %}">Create Account</a>
                </div>
            </h5>
        </div>
    </div>
    <br>

</div>

{% endblock content %}